#!/bin/bash
# NOMARK PRD Runner - Executes PRDs using Claude Code in Ralph autonomous mode
# Creates prd.json and runs the autonomous loop

set -e

PROJECT=$1
PRD_JSON=$2  # Path to prd.json file

# Load environment
if [ -f ~/config/.env ]; then
    export $(cat ~/config/.env | grep -v '^#' | xargs)
fi

# Configure git to use GitHub token for authentication
if [ -n "$GITHUB_TOKEN" ]; then
    git config --global credential.helper store
    git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
fi

if [ -z "$PROJECT" ] || [ -z "$PRD_JSON" ]; then
    echo "Usage: nomark-prd.sh <project> <prd-json-path>"
    exit 1
fi

# Validate project
PROJECT_PATH="$HOME/repos/$PROJECT"
if [ ! -d "$PROJECT_PATH" ]; then
    echo "Project not found: $PROJECT"
    exit 1
fi

# Validate PRD JSON exists
if [ ! -f "$PRD_JSON" ]; then
    echo "PRD file not found: $PRD_JSON"
    exit 1
fi

# Read PRD data
PRD_TITLE=$(jq -r '.title // "PRD Execution"' "$PRD_JSON")
PRD_SUMMARY=$(jq -r '.summary // ""' "$PRD_JSON")

# Change to project directory
cd "$PROJECT_PATH"

# Ensure on main and up to date
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
git checkout "$DEFAULT_BRANCH" 2>/dev/null || git checkout main
git pull origin "$DEFAULT_BRANCH" 2>/dev/null || git pull origin main 2>/dev/null || true

# Create feature branch from PRD title
BRANCH_NAME="ralph/$(echo "$PRD_TITLE" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g' | cut -c1-50)"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

# Create task ID and log
TASK_ID=$(date +%Y%m%d-%H%M%S)
RESULT_FILE="$HOME/logs/prd-${TASK_ID}.json"
mkdir -p ~/logs
echo "[$(date)] [$TASK_ID] Starting PRD: $PRD_TITLE on $PROJECT" >> ~/logs/tasks.log

# Copy PRD to project root for Claude to find
cp "$PRD_JSON" "$PROJECT_PATH/prd.json"
echo "Created prd.json in project root"

# Ensure Claude Code is available
if ! command -v claude &> /dev/null; then
    echo '{"status":"error","error":"Claude Code not installed"}' > "$RESULT_FILE"
    exit 1
fi

# Activate Python venv for any scripts
source ~/venv/bin/activate 2>/dev/null || true

# Run Claude Code in Ralph autonomous mode
claude --dangerously-skip-permissions --print "
You are working on the $PROJECT project in RALPH AUTONOMOUS MODE.

## PRD Loaded
A prd.json has been created in the project root with the full specification.
Read it now with: cat prd.json

## Context
- Project: $PROJECT
- Branch: $BRANCH_NAME
- Task ID: $TASK_ID
- Working directory: $PROJECT_PATH
- Mode: RALPH AUTONOMOUS

## PRD Summary
Title: $PRD_TITLE
$PRD_SUMMARY

## RALPH Autonomous Loop

You MUST follow this autonomous loop until ALL stories in prd.json are complete:

### 1. READ the PRD
cat prd.json
Understand all stories and their acceptance criteria.

### 2. FOR EACH STORY (in order):

   a) Mark story as 'in_progress' in prd.json

   b) IMPLEMENT the story:
      - Write the code
      - Run typecheck: npm run typecheck (or equivalent)
      - Run tests: npm test (or equivalent)
      - Fix any errors

   c) VERIFY the story meets acceptance criteria

   d) COMMIT the changes:
      git add -A
      git commit -m 'feat(story-N): <description>' -m 'Co-Authored-By: NOMARK DevOps <devops@nomark.au>'

   e) Mark story as 'done' in prd.json:
      - Update the status field
      - Save the file

   f) CONTINUE to next story

### 3. AFTER ALL STORIES COMPLETE:

   a) Run full verification:
      - npm run typecheck
      - npm test
      - npm run build (if applicable)

   b) Create PR:
      gh pr create --title '$PRD_TITLE' --body 'Implements PRD: $PRD_TITLE

## Stories Completed
(List all stories from prd.json)

## Changes
(Summary of all changes)

---
Generated by NOMARK DevOps (Ralph Mode)'

## CRITICAL REQUIREMENTS
1. You MUST read prd.json first
2. You MUST implement ALL stories, not just analyze them
3. You MUST update prd.json status after each story
4. You MUST commit after each story (not all at once)
5. You MUST create a PR when all stories are done
6. Do NOT stop until ALL stories are marked 'done'

## Story Status Values
- 'pending' - Not started
- 'in_progress' - Currently working on
- 'done' - Completed and committed
- 'blocked' - Cannot proceed (explain why)

Begin by reading prd.json, then start implementing stories one by one.
"

# Gather results after Claude Code completes
echo "[$(date)] [$TASK_ID] Gathering PRD results..." >> ~/logs/tasks.log

# Check PRD completion status
if [ -f "$PROJECT_PATH/prd.json" ]; then
    TOTAL_STORIES=$(jq '.tasks | length' "$PROJECT_PATH/prd.json" 2>/dev/null || echo "0")
    DONE_STORIES=$(jq '[.tasks[] | select(.status == "done")] | length' "$PROJECT_PATH/prd.json" 2>/dev/null || echo "0")
else
    TOTAL_STORIES=0
    DONE_STORIES=0
fi

# Get changed files
FILES_CHANGED=$(git diff --name-only "$DEFAULT_BRANCH"..."$BRANCH_NAME" 2>/dev/null | head -20 || echo "")
if [ -n "$FILES_CHANGED" ]; then
    FILES_COUNT=$(echo "$FILES_CHANGED" | wc -l | xargs)
else
    FILES_COUNT=0
fi

# Get commit summary
COMMITS=$(git log "$DEFAULT_BRANCH".."$BRANCH_NAME" --oneline 2>/dev/null | head -20 || echo "")
if [ -n "$COMMITS" ]; then
    COMMIT_COUNT=$(echo "$COMMITS" | wc -l | xargs)
else
    COMMIT_COUNT=0
fi

# Check for PR
PR_URL=$(gh pr view "$BRANCH_NAME" --json url -q '.url' 2>/dev/null || echo "")

# If no PR exists but there are commits, create one
if [ -z "$PR_URL" ] && [ "$COMMIT_COUNT" -gt 0 ]; then
    git push -u origin "$BRANCH_NAME" 2>/dev/null || true

    PR_BODY="## PRD: $PRD_TITLE

$PRD_SUMMARY

**Stories:** $DONE_STORIES/$TOTAL_STORIES completed
**Branch:** \`$BRANCH_NAME\`
**Task ID:** \`$TASK_ID\`

## Commits
$COMMITS

## Files Changed
\`\`\`
$FILES_CHANGED
\`\`\`

---
Generated by NOMARK DevOps (Ralph Mode)"

    PR_URL=$(gh pr create --title "$PRD_TITLE" --body "$PR_BODY" --head "$BRANCH_NAME" 2>/dev/null | grep -oE 'https://github.com/[^ ]+' || echo "")
fi

# Get insertions/deletions
DIFF_STATS=$(git diff --stat "$DEFAULT_BRANCH"..."$BRANCH_NAME" 2>/dev/null | tail -1 || echo "")
INSERTIONS=$(echo "$DIFF_STATS" | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo "0")
DELETIONS=$(echo "$DIFF_STATS" | grep -oE '[0-9]+ deletion' | grep -oE '[0-9]+' || echo "0")

# Determine completion status
if [ "$DONE_STORIES" -eq "$TOTAL_STORIES" ] && [ "$TOTAL_STORIES" -gt 0 ]; then
    COMPLETION_STATUS="complete"
    NEXT_ACTIONS="All stories complete! Review and merge the PR."
elif [ "$DONE_STORIES" -gt 0 ]; then
    COMPLETION_STATUS="partial"
    NEXT_ACTIONS="$DONE_STORIES/$TOTAL_STORIES stories complete. Continue with remaining tasks."
else
    COMPLETION_STATUS="not_started"
    NEXT_ACTIONS="No stories completed. Check logs for issues."
fi

# Build JSON result
cat > "$RESULT_FILE" << EOF
{
  "status": "success",
  "mode": "ralph",
  "task_id": "$TASK_ID",
  "project": "$PROJECT",
  "branch": "$BRANCH_NAME",
  "prd_title": "$PRD_TITLE",
  "pr_url": "$PR_URL",
  "stories_total": $TOTAL_STORIES,
  "stories_done": $DONE_STORIES,
  "completion_status": "$COMPLETION_STATUS",
  "commits": $COMMIT_COUNT,
  "files_changed": $FILES_COUNT,
  "insertions": ${INSERTIONS:-0},
  "deletions": ${DELETIONS:-0},
  "files": $(echo "$FILES_CHANGED" | jq -R -s 'split("\n") | map(select(length > 0))'),
  "commit_messages": $(echo "$COMMITS" | jq -R -s 'split("\n") | map(select(length > 0))'),
  "next_actions": "$NEXT_ACTIONS"
}
EOF

# Log completion
echo "[$(date)] [$TASK_ID] Completed PRD: $PRD_TITLE ($DONE_STORIES/$TOTAL_STORIES stories)" >> ~/logs/tasks.log

# Output result file path for the bot to read
echo "RESULT_FILE:$RESULT_FILE"
